<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gd</string>
	</array>
	<key>name</key>
	<string>GDScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gdscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.gdscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.quoted.double.gdscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>(?&lt;!\\)'</string>
			<key>name</key>
			<string>string.quoted.single.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:0x\h*)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.float.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\.\d+(e[\-\+]?\d+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.float.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))\b</string>
			<key>name</key>
			<string>constant.numeric.float.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:elif|else|for|if|while|break|continue|pass|return)\b</string>
			<key>name</key>
			<string>keyword.control.flow.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:&amp;&amp;|and|in|is|!|not|\|\||or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|==|&lt;|&gt;|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=|-=|\*=|/=|%=|&amp;=|\|=|\*|/|%|\+|-|&lt;&lt;|&gt;&gt;|&amp;|\||\^|~</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.gdscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.gdscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?i:(class))\s+([a-zA-Z_][a-zA-Z_0-9]*)\s*:</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i:(func))\s+([a-zA-Z_][a-zA-Z_0-9]*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gdscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\s*:</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z_0-9]*</string>
					<key>name</key>
					<string>variable.parameter.gdscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.var.gdscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.gdscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(var))\s+([a-zA-Z_][a-zA-Z_0-9]*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.const.gdscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*\b(?i:(const))\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(?i:extends))\b</string>
			<key>name</key>
			<string>keyword.other.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=extends)\s+[a-zA-Z_][a-zA-Z_0-9]*(\.([a-zA-Z_][a-zA-Z_0-9]*))?</string>
			<key>name</key>
			<string>entity.other.inherited-class.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:true|false)\b</string>
			<key>name</key>
			<string>constant.language.gdscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:static|export|tool)\b</string>
			<key>name</key>
			<string>storage.modifier.static.gdscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gdscript</string>
	<key>uuid</key>
	<string>e08b7d98-5d50-4aa9-8935-7c759a4a8fdd</string>
</dict>
</plist>
